### ISSUE TITLE
Peer to peer code review: Week 5 of 5

### ISSUE THREAD

**Issue by annaeliana7** [PrantoshB/RSM-Mathematics-Exhibition-2022#2]
### Fantastic Job @PrantoshB !!! 🏆 

Your RSM Mathematic Exhibition site looks incredible!! 🎓 🤓

There are two minor suggestions to polish your project: 

- Your README description already has a title, therefore your description does not need to bold the title again, or have it in brackets on the next line. My suggestion would be to remove the brackets and unbold it to make it flow in a regular paragraph
<img width="869" alt="1  README Description" src="https://user-images.githubusercontent.com/112557951/203721999-1101b5ab-4b7e-4d6b-a651-9c4ed9fa7081.png">

- Since you have merged your file, and completed your project, you can delete the branch. This would make your repository complete and would look professional 
<img width="1252" alt="2  Merge" src="https://user-images.githubusercontent.com/112557951/203722120-12f45918-229c-4925-9913-0083bd9e16be.png">

All around, you did a FANTASTIC job!! Congratulations 🎉 🎉 🎉

**Comment by PrantoshB** [comment]
> ### Fantastic Job @PrantoshB !!! 🏆
> Your RSM Mathematic Exhibition site looks incredible!! 🎓 🤓
> 
> There are two minor suggestions to polish your project:
> 
> * Your README description already has a title, therefore your description does not need to bold the title again, or have it in brackets on the next line. My suggestion would be to remove the brackets and unbold it to make it flow in a regular paragraph
> 
> <img alt="1 README Description" width="869" src="https://user-images.githubusercontent.com/112557951/203721999-1101b5ab-4b7e-4d6b-a651-9c4ed9fa7081.png">
> 
> * Since you have merged your file, and completed your project, you can delete the branch. This would make your repository complete and would look professional
> 
> <img alt="2 Merge" width="1252" src="https://user-images.githubusercontent.com/112557951/203722120-12f45918-229c-4925-9913-0083bd9e16be.png">
> 
> All around, you did a FANTASTIC job!! Congratulations 🎉 🎉 🎉

Hello @annaeliana7 , 
Thanks for the beautiful comments. 🙇🏽
I have fixed the issues mentioned above 👨🏻‍💻

Cheers,
Prantosh B
